version: '3.1'

services:
  sandwich-db:
    image: postgres:9.6.13
    environment:
      POSTGRES_PASSWORD: sandwichadmin
      POSTGRES_USER: sandwichadmin
      POSTGRES_DB: sandwichdb
    expose:
      - 5432
    ports:
      - 5000:5432

  ingredient-db:
    image: postgres:9.6.13
    environment:
      POSTGRES_PASSWORD: ingredientadmin
      POSTGRES_USER: ingredientadmin
      POSTGRES_DB: ingredientdb
    expose:
      - 5432
    ports:
      - 5001:5432

  emoji-db:
    image: postgres:9.6.13
    environment:
      POSTGRES_PASSWORD: emojiadmin
      POSTGRES_USER: emojiadmin
      POSTGRES_DB: emojidb
    expose:
      - 5432
    ports:
      - 5002:5432

  food-mq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: wabbit
      RABBITMQ_DEFAULT_PASS: wabbit
    expose:
      - 5672
      - 15672
    ports:
      - 5003:5672
      - 15002:15672
